LSM6DSOX - Get Configuration
leka/LekaOS_Explorations pull request #10
Opened 2020-05-18 08:30 UTC by YannLocatelli

Le but est de sortir une version avec une simple connexion i2c et récupérer la configuration.
La difficulté ici est d'utiliser le driver et de faire une bonne première structure.

2020-05-18 08:33 UTC, YannLocatelli commented
Il manque l'intégration avec les nouvelles fonctions proposées par le driver situées dans le `group Basic Configuration` (ligne 9474)

2020-05-18 08:42 UTC, YannLocatelli commented
Aussi, il y a une redondance dans l'utilisation de l'I2C entre l'accéléromètre et le gyroscope qui peut être allégé avec une nouvelle classe qui gèrera n'importe quelle interface I2C.

Exemple:
Accelerometer [[Ligne 58 à 99](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h#L58-L99)] avec Gyroscope [[Ligne 58 à 99](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h#L58-L98)]

2020-05-18 09:45 UTC, ladislas commented
> Il manque l'intégration avec les nouvelles fonctions proposées par le driver situées dans le `group Basic Configuration` (ligne 9474)

@YannLocatelli tu peux mettre le lien?

2020-05-18 09:57 UTC, ladislas commented
> Aussi, il y a une redondance dans l'utilisation de l'I2C entre l'accéléromètre et le gyroscope qui peut être allégé avec une nouvelle classe qui gèrera n'importe quelle interface I2C.
> 
> Exemple:
> Accelerometer [[Ligne 58 à 99](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h#L58-L99) [](/leka/LekaOS_Explorations/blob/HEAD@{2020-05-18T08:42:09Z}/LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h#L58-L99)] avec Gyroscope [[Ligne 58 à 99](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h#L58-L98) [](/leka/LekaOS_Explorations/blob/HEAD@{2020-05-18T08:42:09Z}/LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h#L58-L98)]

@YannLocatelli il y a plusieurs solutions:

1. soit faire une classe `LKI2C` ou `SensorI2C` qui hérite de mbed `I2C` et qui ajoute les deux méthodes (attention aux `_address` qui sera pas dispo et qu'il faudra avoir en paramètre
1. soit avoir une interface `SensorBase` qui propose des [`virtual` functions](https://stackoverflow.com/a/2392656/2205264) dans la déclaration et dont `Accelerometer` et `Gyroscope` héritent et qui peuvent les redéfinir en `private` (parce qu'on a pas besoin de l'appeler directement normalement).
1. on doit même pouvoir avoir `SensorBase` qui définit les deux méthodes en `private` directement

Je testerai la `3.` pour voir, ça me semble le mieux.

2020-05-18 10:01 UTC, ladislas commented
> Je testerai la 3. pour voir, ça me semble le mieux.

Quoi que... maintenant que j'écris ça, je suis pas sûr que d'avoir une class `SensorBase` face sens parce que ça voudrait dire prendre en compte tous les capteurs.

Dans le cas là, on voit qu'on utilise deux fois la même chose mais c'est parce que c'est le même composant.

Si on avait eux deux composants différents, on aurait peut être un en i2c et l'autre en spi, on se dirait pas qu'on a deux fois le même.

C'est du code qu'on va pas réécrire plusieurs fois et qui est hardware spécifique, ça me choque en fait pas qu'il soit dédoublé. On peut laisser pour le moment.

2020-05-18 10:19 UTC, YannLocatelli commented
Le lien pour le `group Basic Configuration` a été mis à jour, on peut le retrouve ici aussi -> [[Lien]](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/driver-lsm6dsox/lsm6dsox_reg.c#L9474-L11877)

Pour ce qui est de l'I2C, la structure actuelle sera la même pour les composants en I2C de ST vus jusque là, de sûr ça concernera le LSM303AGR et le HTS221 à minima. Sans oublier qu'elle sera encore dédoublée pour les classes MLC et FSM du LSM6DSOX à venir.

> C'est du code qu'on va pas réécrire plusieurs fois et qui est hardware spécifique, ça me choque en fait pas qu'il soit dédoublé. On peut laisser pour le moment.

Je reste sur ça pour le moment, ça sera un point à revoir si on redéfinie la structure.

2020-05-19 07:55 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	assert (i2c);
il faudra bien vérifier qu'on compile après avec `NDEBUG` https://en.cppreference.com/w/cpp/error/assert

voir aussi si c'est conseillé en dehors des tests de mettre des assert dans le code. pas sûr que ce soit utile de crasher le robot si l'i2c ne marche plus. on voudrait plutôt continuer en faisant remonter le problème.

2020-05-19 12:30 UTC, ladislas requested changes

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +## Abreviation
peux tu mettre la source des abréviations? :)

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +* UI : User Interface
c'est drôle `ui`, je comprends pas beaucoup à quoi ça correspond. C'est pour faire du "téléphone tourné à 90° à gauche" ?

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	switch((_status.ui.xl.odr & 0x0F))
pour du code comme `_status.ui.xl.odr & 0x0F` il faut expliquer pourquoi on fait ça et ce que ça veut dire.

On peut le savoir maintenant mais si on revient 15 jours après je suis sûr qu'on aura oublié ;)

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	*powerMode 	= (*dataRate == 0)						?	Power_Off_Acc
le ternary operator c'est rigolo mais c'est pas très clair quand c'est chainé comme ça.

Ca serait pas mal de le mettre en en `if/else` même si c'est deep nested.

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +LSM6DSOXAccStatusTypeDef Accelerometer::get_int_status(uint8_t *dataReady)
le nom de la fonction est pas clair et ce qu'elle fait ne sont pas clair pour moi.
tu dis `get_int_status` mais en même temps tu récupères des données en passant un pointeur.

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	return success;
pourquoi définir un `success` plutôt que juste `return LSM6DSOX_Acc_OK` comme tu le fais déjà dans le `if`.

et surtout que tu dis que tu vas récupérer le status de l'interrupt (donc s'il y a des données dispos) mais qu'en fait tu get le status de l'accéléromètre au sens large.

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
il faut préféré les `enum class`, voir ici: http://www.stroustrup.com/C++11FAQ.html#enum

C'est Bjarn lui même qui le dit ;)

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +	High_Performance_Acc = 0,
le `_Acc` à chaque fois est redondant avec le nom de l'enum.
La valeur aussi sauf si on s'en sert quelque part. Peut être lui donner un type aussi alors.

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.cpp
> +	switch((_status.ui.gy.odr & 0x0F))
même remarque sur pourquoi et à quoi ça sert le `&`

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Accelerometer *accelerometer)
je renommerai en `testAccelerometerStatus`

2020-05-19 12:30 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Gyroscope *gyroscope)
je renommerai en `testGyroscopeStatus`

2020-05-19 13:02 UTC, ladislas requested changes

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
de même que pour l'autre, préférer une `enum class` :

```cpp

enum class AccStatus { // drop the LSM6DSOX
	ok    =  0,
	error = -1
}

```

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +	High_Performance_Acc = 0,
on peut simplifier par:

```cpp

enum class AccPowerMode {
	normal,
	low,
	ultra_low,
	off
}

```

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
pareil ici:

```cpp
enum class AccTransmissionStatus {
	ok       =  0,
	error    = -1,
	overflow = -2
}
```

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
et d'ailleurs pourquoi -1 et -2 plutôt que 1 et 2?

0 c'est que tout est OK mais une raison particulière à aller dans le négatif?

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
même remarque pour `enum class`

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
même remarque pour `enum class`

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +//	Ultra_Low_Power_Gyro = 3,
pas de ultra low power? comment c'est possible?

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
même remarque pour `enum class`

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->read_id(&id);
`success` c'est bizarre parce que si c'est pas success tu as `successs == error`.

ST utilise `ret`, on peut aussi avoir `status` (mais ne pas confondre avec les autres).

tu dois pouvoir faire `auto ret = accelerometer->read_id(&id);` comme ça tu gagnes un lignes, le `ret` prend automatiquement le bon type, et on prend l'habitude de l'écrire comme ça. à chaque fois.

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    if (success == LSM6DSOX_Acc_OK && id == LSM6DSOX_ID) {
si vraiment on voulait utiliser `success` (mais je suis contre) ça ferait plus sens de juste mettre `if (success && id == LSM6DSOX_ID)`

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    LSM6DSOXGyroStatusTypeDef success;
pareil pour le nom ici.

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +#define PIN_I2C_SDA                 (D14)
je préfère les `constexpr` que les `#define`, au moins le compilateur peut les checker.

2020-05-19 13:02 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->get_int_status(&dataReady);
c'est quoi la nature de `dataReady`?

2020-05-19 14:03 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +LSM6DSOXAccStatusTypeDef Accelerometer::get_int_status(uint8_t *dataReady)
une autre manière de découper pourrait être la suivante 👍 

```cpp
bool dataAvailable() {
	if (lsm6dsox_all_sources_get(&_reg_ctx, &_int_status) == LSM6DSOX_Acc_OK) { // on check pour le positif, c'est plus naturel (en général)
		// et on return true si c'est ok
		return true;
	}
	else { // on garde le else pour bien montrer que c'est l'un ou l'autre.
		return false;
	}
}

// et plus tard dans le code

if (dataAvailable()) {
	auto ret = getAvailableData(&newData);
	if (ret == status::ok) {
		analyzeData(&newData);
	}
}
```

2020-05-19 14:28 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +## Abreviation
Elles sont indiquées dans la [datasheet](https://www.st.com/resource/en/datasheet/lsm6dsox.pdf), elles sont implicites comme explicites.

Je l'ajoute dans le prochain commit dans le README.md

2020-05-19 14:32 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +* UI : User Interface
Le terme reste flou aussi pour moi, et pourtant j'ai passé pas mal d'heures à l'utiliser. Tout ce que je peux dire c'est qu'il fortement lié au `ois`dans le code.

2020-05-19 14:38 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +* UI : User Interface
ok, en lisant la datasheet, je comprends que eis et ois sont deux modes pour la stabilisation optique dans des caméras. J'imagine qu'il y a un protocole et une norme pour ça et que tu peux activer le mode pour le capteur afin qu'il sorte les données que la camera peut utiliser directement.

donc complètement inutile dans notre cas :)

2020-05-19 14:44 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	return success;
Tout à fait pour le `success`, ça a été corrigé dans le commit https://github.com/leka/LekaOS_Explorations/commit/1ec5825d2295d562b0caffa3e04763fae58f66a9

> tu dis que tu vas récupérer le status de l'interrupt (donc s'il y a des données dispos) mais qu'en fait tu get le status de l'accéléromètre au sens large.

C'est effectivement pas la bonne forme pour utiliser les interrupts. Quand j'ai voulu intégrer tous les `status` je me suis retrouvé avec la fonction `all_sources_get`et qui menait à la fin à tous les interrupts du composant. Dans le cas de l'accéléromètre il n'y en a qu'un qui lui est proprement utile.

2020-05-19 14:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Accelerometer *accelerometer)
Je resterai sur un même nom afin de fusionner cette fonction avec celle du gyroscope afin d'en avoir qu'une seule au lieu de deux, c'est pour ça que je suis resté sur un nom identique.

2020-05-19 14:56 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
L'idée d'affecter des `enum` pour les OK/ERROR vient du stm32duino. Et ils avaient basé leur ERROR à -1.

Par contre je doute que ça ait plus de sens d'aller dans les négatifs, donc on peut aller dans les positifs sans soucis si ça a un intérêt d'optimisation.

2020-05-19 14:56 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +//	Ultra_Low_Power_Gyro = 3,
Pas pour le gyroscope :) (cf. datasheet)

2020-05-19 14:59 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    if (success == LSM6DSOX_Acc_OK && id == LSM6DSOX_ID) {
En dehors du nom de variable `success`, ça ne fonctionnerait pas parce qu'en cas de "succès" la valeur est à 0.... donc ça ferrait sauter la condition directement.

2020-05-19 15:06 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/README.md
> +* UI : User Interface
Oui, et `ui` correspond au mode par défaut, sans caméra donc.

On sera en Mode 2 (avec capteur externe) et jamais en Mode 3 ou Mode 4 (avec caméra)

2020-05-19 15:09 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
l'intérêt de donner un numéro c'est qu'après on peut checker l'error avec `try-block`.

Si on a des errors spécifiques à nous, on peut faire un enum. sinon c'est bien aussi d'utiliser les exceptions de `std::` https://en.cppreference.com/w/cpp/error/exception qui intègre overflow et runtime error par exemple.

2020-05-19 15:12 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    if (success == LSM6DSOX_Acc_OK && id == LSM6DSOX_ID) {
dans ce cas là il faut utiliser `auto outputStatus` comme ça c'est clair pour tout le monde et on se pose plus de questions.

2020-05-19 15:14 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Accelerometer *accelerometer)
okay, et dans ce cas là, qu'apporte le `All`?

tu testes quoi dans cette méthode ?

2020-05-19 15:21 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +//	Ultra_Low_Power_Gyro = 3,
ok

2020-05-19 15:29 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Accelerometer *accelerometer)
De base il n'y avait que les `status` puis les `int_status` se sont ajoutés. Donc pour éviter une confusion j'ai mis `All`.
Après la restructuration, les interrupts seront considéré à part entière et il ne restera plus que les `status` normaux, le `All` perdra alors son sens.

2020-05-19 16:34 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +void testAllStatus(Accelerometer *accelerometer)
justement je comprends pas bien ce découpage.

je pense (en relisant le code) que le problème vient aussi de `status` qui est pas vraiment le `status` (ouvert ou fermé, on/off, etc.) mais plutôt une `config` qui d'ailleurs serait mieux encapsulée dans une `struct` (pour le futur c'est mieux).

Ensuite tu `get_config()` tout simplement si vraiment tu veux la récupérer quelque part. 

Mais surtout, que ce soit en détails ou en struct, tout ça doit être des member variables (donc dans la classe) et tu dois pouvoir les récupérer avec `get_power_mode()`

Ca pose la question du error handling. A mon sens dans le design final, quand tu utiliseras accelerometer, tu veux pas avoir à savoir si l'accelerometer marche ou pas. si ça marche pas, ça doit s'arrêter et être remonté à un ErrorHandler au niveau de l'application qui pourra le transmettre à l'iPad.

C'est un vaste sujet qu'il faudra définir.

2020-05-19 16:48 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	switch((_status.ui.xl.odr & 0x0F))
Merci, ça a été ajouté dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:48 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	*powerMode 	= (*dataRate == 0)						?	Power_Off_Acc
Merci, ça a été ajouté dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:49 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
Ca a été ajouté dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

Même si ça allège le nom, les comparaison (avec `!=`) ne passe plus, je suis obligé de cast à chaque comparaison avec des éléments externes.

2020-05-19 16:49 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +	High_Performance_Acc = 0,
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.cpp
> +	switch((_status.ui.gy.odr & 0x0F))
Le commentaire a été ajouté dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:50 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/gyroscope/gyroscope.h
> +typedef enum
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:51 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->read_id(&id);
Tous les `success` ont été retiré et ont été remplacé dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:51 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    if (success == LSM6DSOX_Acc_OK && id == LSM6DSOX_ID) {
Tous les `success` ont été retiré et ont été remplacé dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b

2020-05-19 16:59 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->get_int_status(&dataReady);
Tu entends quoi par nature?

2020-05-19 17:31 UTC, YannLocatelli reviewed
Commentaires sur les difficultés rencontrés pour cet issue et de suggestions pour la suite.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +}
Mentionné dans un appel, il serait intéressant de rentrer cette fonction à l'intérieur de la classe afin de simplifier son utilisation.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +        printf("Output Data Rate is (approximately) %dHz\r\n", (int)dataRate); //printf does not handle float, dataRate was reduced to int
Sous mbed, `printf()` n'arrive pas à afficher directement un `float`. Ca a été casté en `int` ici et n’est pas indispensable pour l’utilisation normal mais prévoir une meilleur alternative pour plus tard.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	//*mg_Z = _data.ui.xl.mg[2];
L'utilisation de la fonction `lsm6dsox_data_get()` a été abandonnée, il y a encore trop d'erreur dans cette fonction.
Je ferrai remonté les erreurs en temps libre.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	_status.ui.xl.fs  = _status.ui.xl.LSM6DSOX_XL_UI_4g;
La forme est illisible, la faute à un `enum` anonyme imbriquée dans plusieurs `struct` anonymes. Le côté anonyme signifie qu'il n'y a pas de nom, ça n'empêche pas d'avoir un type.
On peut retrouver ladite structure [ici](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/driver-lsm6dsox/lsm6dsox_reg.h#L3129-L3251).

Si il y a un moyen d'accéder au `enum` sans passer avoir les autres `struct` je suis preneur.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +		return AccStatus::ERROR;
La fonction proposée dans le driver récupère **TOUTE** la configuration, contrairement à la version sous mbed qui configure **UN PAR UN** chaque paramètre.

La raison pour laquelle il n'y a pas de `set_status` est dû au choix à faire entre ces deux manières (configurer tous les paramètres en une fois ou un par un).

Il faut aussi prendre en compte un commentaire fait plus haut qui implique un accès lourd aux valeurs (`enum`) de la configuration.

2020-05-19 17:31 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	}
Il n'existe pas de `struct`/`enum` pour associer la fréquence à un `float`. Seulement est disponible un identifiant en hexadecimal qui est reconvertis ici.

Il faudra donc prévoir une fonction ou un dictionnaire (`map` en C++) pour convertir dans les deux sens plus facilement, accessible de partout puisque ces paramètres seront souvent réutilisés.

2020-05-20 07:14 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
tu peux donner un type à ton enum avec `enum class: uint8_t` par exemple.

testes et dis moi si ça marche :)

2020-05-20 07:16 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->get_int_status(&dataReady);
qu'est-ce que ça représente? c'est quoi comme data? comment je peux l'utiliser?

2020-05-20 07:21 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +        printf("Output Data Rate is (approximately) %dHz\r\n", (int)dataRate); //printf does not handle float, dataRate was reduced to int
c'est parce que de base, c'est minimal printf qui est utilisé et qui effectivement ne print pas les float pour limiter la taille mémoire que ça prend (j'ai pu les chiffres le float fait passer du simple au double voir pire).

pour le moment on touche pas, on garde le minimal et on verra par la suite.

2020-05-20 07:21 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	//*mg_Z = _data.ui.xl.mg[2];
curieux de voir les erreurs! :)

2020-05-20 07:23 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	_status.ui.xl.fs  = _status.ui.xl.LSM6DSOX_XL_UI_4g;
si tu parles de `_status.ui.xl.odr` je ne suis pas d'accord, pour le coup c'est ultra standard comme forme (on peut reprocher les abréviations pas claires mais c'est très spécifique), avec les `.`. En Swift on aura que ça.

Pour le coup je trouve que leur structure est assez propre.

De toute manière, ce genre de chose ne sera écrit qu'une fois et bien documenté. Après on en parlera plus.

2020-05-20 07:51 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +		return AccStatus::ERROR;
je pense que le problème vient surtout du design et du manque d'encapsulation.

ta `class Accelerometer` devrait avoir en `private member`:

- soit une struct `config`
- soit des membres séparés

```cpp

// Soit une struct - plus propre je trouve
struct AccelerometerConfig {
	AccPowerMode powerMode,
	float dataRate,
	uint16_t scale,
}

class LSM6DSOXAccelerometer { // ⚠️ je pense que c'est important de renommer les classes actuelles avec le prefix `LSM6DSOX` pour bien montrer le `tight coupling`

public:

	// ... code

	// Soit tu get la config au total dans une struct bien définie
	void getConfig(AccelerometerConfig * config);
	// Soit tu get les données individuelles
	// tu peux d'ailleurs faire les deux si besoin, c'est pas l'un ou l'autre
	AccPowerMode getPowerMode();
	float getDataRate();
	uint16_t getScale();

	// et tu peux faire pareil avec le set
	void setConfig(AccelerometerConfig * config) {
		_config = * config;
	}
	void setPowerMode(AccPowerMode mode) {
		// Soit
		_config.powerMode = mode;
		// ou
		_powermode = mode;
	}

private:
	// Soit une struct - plus propre je trouve
	Config _config;

	// Soit des membres séparés
	AccPowerMode _powerMode,
	float _dataRate,
	uint16_t _scale,

```

2020-05-20 08:00 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	}
tu peux me pointer dans la doc où tout ça est décrit?

2020-05-20 08:38 UTC, ladislas commented
@YannLocatelli j'ai refait un passage ce matin au réveil après une grande tasse de café.

Il y a plusieurs choses qui me chiffonnent ;)

1. la séparation de accéléromètre et gyroscope alors qu'ils devraient être dans la même classe LSM6DSOXSensor
1. la duplication de beaucoup de code (due au 1.)
1. une confusion sur le nom des choses par exemple `status` qui n'est pas vraiment un état
1. le manque de parallélisme entre getter et setter qui crée de la confusion
1. un manque d'encapsulation et de routines pour permettre une meilleure abstraction
1. enfin, il y a une différence entre le nom de la PR et ce que fait le code

Tous ces points vont dans le sens du "on a été trop vite, on est pas parti dans le bon sens".

Heureusement, pour résoudre tout ça, il suffit de faire ce qu'on aurait du faire dès le début... 🥁 

> un schéma ! 🎉

Commençons par ça, un papier, un crayon, et un schema qui explique ce qu'on va faire et pourquoi on va le faire.

2020-05-20 08:42 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h
> +typedef enum
Ca a déjà été fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/10/commits/34c9ea8fc271c187a36c64caf0c9a11bc8bd7c4b, comme on peut le voir ici : [[Lien](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.h#L24-L41)]

2020-05-20 08:42 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/src/main.cpp
> +    success = accelerometer->get_int_status(&dataReady);
C'est relié à l'interrupt, il représente l'état de l'interrupt "Data Ready" de l'accéléromètre.

Dans l'état actuel il n'a que peu d'intérêt puisqu'au lieu de recevoir une notification au travers d'un interrupt (`INT1` ou `INT2` du LSM6DSOX), il y a un aller-retour pour aller l'interroger.

En dehors des pins interrupts, il pourra être utilisé avant de récupérer la data. Dans ce cas là, l'utilisateur n'aura pas besoin d'avoir connaissance de ce flag.

2020-05-20 08:42 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	_status.ui.xl.fs  = _status.ui.xl.LSM6DSOX_XL_UI_4g;
Je parlais plus de la partie droite de l'affectation : `_status.ui.xl.LSM6DSOX_XL_UI_52Hz_LP`

On peut voir une redondance des termes `ui` et `xl` et la valeur de l'enum ne peut être affecté qu'à partir d'un objet, ici `_status`.
Ca implique que laissé tel quel, pour passer en paramètre il faut entrer `_status.ui.xl.LSM6DSOX_XL_UI_52Hz_LP` plutôt que simplement `LSM6DSOX_XL_UI_52Hz_LP`

2020-05-20 08:42 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +		return AccStatus::ERROR;
En fait, `_status` est le `_config` de ton exemple et la struct `lsm6dsox_md_t` [[Lien vers sa définition](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/driver-lsm6dsox/lsm6dsox_reg.h#L3129-L3251)] qui correspond à la struct `Config` dans ton exemple...

La question porte plus sur l'utilisation d'une telle struct ou de tout découper. On est favorable à une struct plutôt que des membres séparés, mais soit :
* on utilise la struct `lsm6dsox_md_t` proposé par le driver avec l'inconvénient mentionné [un peu plus haut](https://github.com/leka/LekaOS_Explorations/pull/10#discussion_r427470560), 
* on réécrit une struct (exemple `Config`) pour d'une part palier au soucis du point précédent et d'autre part ajouter des paramètres supplémentaires tel que le `PowerMode`.

Bien que la seconde nécessite plus de travail et de code, il permettra d'avoir un code plus clair.

2020-05-20 08:43 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	}
Au niveau du code on retrouve leur définition ici : [[Lien](https://github.com/leka/LekaOS_Explorations/blob/yann-Sensors-LSM6DSOX-Get_Configuration/LKExp-Sensors-LSM6DSOX_Examples/lib/driver-lsm6dsox/lsm6dsox_reg.h#L3133-L3155)]
Dans la [datasheet](https://www.st.com/resource/en/datasheet/lsm6dsox.pdf), tu peux le retrouver en Table 51 (p.56)

2020-05-20 08:47 UTC, ladislas commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	}
ah je comprends ! en fait tu veux fair ressortir le data rate dans un format qu'on peut lire?

2020-05-20 14:55 UTC, YannLocatelli commented
Je me permets de remettre ici ce que j'ai pu en partie dire par téléphone:

* Le fait de séparer accéléromètre et gyroscope a été un choix fait au début. La nécessité de suivre une structure en Dependency Inversion Principle (DIP) ne s'est révélée que récemment. Par ailleurs ce code servira d'exemple pour le futur.  
Pour prévenir de problèmes similaires, voir la **proposition de solution [1]**
* Jusqu'alors le code permettait d'identifier les obstacles au niveau du code qui seront à anticiper dans la version suivante. Je prends pour exemple la fonction `lsm6dsox_data_get()` inutilisable actuellement et qui conduit à trouver une alternative.  
Toutefois il est vrai que le code manquait de clarté notamment sur les termes employés.
Pour prévenir de problèmes similaires, voir la **proposition de solution [2]**
* Dans la même veine, le code est très linéaire (peu/pas d'utility) afin d'illustrer au mieux les besoins futurs. Le choix de ne pas rendre le code complexe a malheureusement conduit à le rendre plus obscure.
Les futurs code ne passeront plus par cette étape. Par ailleurs les simplicités volontairement utilisés ici seront ajoutés à la **proposition de solution [1]**.
* Enfin il est vrai que le nom de la PR n'est pas adéquat au vus des objectifs fixés dans l'issue https://github.com/leka/LekaOS_Explorations/issues/11 qui je l'admets ne sont pas des plus claires.
Pour prévenir de problèmes similaires, voir la **proposition de solution [2]**


**Proposition de solution [1]**  
Rédiger un document et/ou un wiki pour décrire les bonnes pratiques et les "erreurs" déjà commises.
Il(s) peut(vent) compléter un document existant déjà: [Règles de codage C++](https://github.com/leka/moti-core/blob/master/docs/common/L-DI-RDC-CPP.pdf).

**Proposition de solution [2]** (discuté par téléphone)  
La première étape est de réaliser un cahier des charges avec des diagrammes associés pour :

* décrire l'architecture (ex. avec un diagramme de classe),
* expliciter les différents objectifs (ex. avec un diagramme de cas d'utilisation)


En attendant de répondre à ces demandes, je ferme cette PR.

2020-05-20 14:55 UTC, closed without merging

2020-06-05 12:22 UTC, YannLocatelli commented on LKExp-Sensors-LSM6DSOX_Examples/lib/accelerometer/accelerometer.cpp
> +	//*mg_Z = _data.ui.xl.mg[2];
Fixed : https://github.com/STMicroelectronics/STMems_Standard_C_drivers/issues/62 :)