Initial commit
leka/LekaOS_Explorations pull request #5
Opened 2020-05-07 23:50 UTC by YannLocatelli

2020-05-08 14:48 UTC, ladislas commented
Whaou merci @YannLocatelli ! :) 

Est-ce qu'il est possible d'enlever tout le BSP de ST et de remettre que ce dont on a besoin ?

Je vois qu'il y a beaucoup de fichier dont on a pas vraiment besoin, genre audio.h.

2020-05-08 15:01 UTC, ladislas requested changes
première review en plus des mes commentaires précédents sur l'intégralité du BSP

2020-05-08 15:01 UTC, ladislas commented on LKExp-mbed-sensors/src/main.cpp
> +Board *board = new Board();
pourquoi tu fais un pointer?

et pas juste `Board board;`

2020-05-08 15:01 UTC, ladislas commented on LKExp-mbed-sensors/src/main.cpp
> +    board->check_id();
ça permettrait ici de faire `board.check_id()`

2020-05-08 15:01 UTC, ladislas commented on LKExp-mbed-sensors/src/board.cpp
> +    dev_i2c = new DevI2C(sda, scl);
même question d'instantiation ici : avec new tu crées les objets dans heap et donc tu dois pas oublier d'appeler delete quand tu as fini.

Pourquoi ne pas faire l'instantiation avec le constructeur pour être dans le stack?

2020-05-11 15:32 UTC, YannLocatelli commented on LKExp-mbed-sensors/src/board.cpp
> +    dev_i2c = new DevI2C(sda, scl);
Effectivement, le heap pourrait être allégé, je modifie ça dans les prochaine commit

2020-05-11 15:32 UTC, YannLocatelli commented on LKExp-mbed-sensors/src/main.cpp
> +Board *board = new Board();
J'avais repris la structure de l'exemple de ST.
Ca sera modifié dans le prochain commit.

2020-05-11 17:24 UTC, YannLocatelli commented
> Est-ce qu'il est possible d'enlever tout le BSP de ST et de remettre que ce dont on a besoin ?  

Ladislas, https://github.com/leka/LekaOS_Explorations/pull/5#issuecomment-625852173
A été réalisé dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/5d3694f7b31e45f2ff22ff0df4b5e0e85f744ff7

2020-05-11 17:25 UTC, YannLocatelli commented on LKExp-mbed-sensors/src/main.cpp
> +Board *board = new Board();
Fait dans le commit https://github.com/leka/LekaOS_Explorations/commit/6225ef1acbb533831755b1d813531bc9bac1a532

2020-05-11 17:25 UTC, YannLocatelli commented on LKExp-mbed-sensors/src/main.cpp
> +    board->check_id();
Fait dans le commit https://github.com/leka/LekaOS_Explorations/commit/6225ef1acbb533831755b1d813531bc9bac1a532

2020-05-11 17:25 UTC, YannLocatelli commented on LKExp-mbed-sensors/src/board.cpp
> +    dev_i2c = new DevI2C(sda, scl);
Fait dans le commit https://github.com/leka/LekaOS_Explorations/commit/6225ef1acbb533831755b1d813531bc9bac1a532

2020-05-12 13:36 UTC, ladislas requested changes
merci Yann! Sans le BSP c'est beaucoup plus clair! C'est intéressant parce qu'on voit qu'ils ont fait un peu comme on voulait faire (et dont on parlait hier), ils ont plusieurs couches:

- driver de bas niveau, par exemple `dsox_reg`
- une interface par exemple, `MagneticSensor`
- la capteur final qui implemente l'interface en utilisant les drivers, par exemple `LSM303AGRMagSensor.h`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/HTS221/.lock/pid
> +10056
essayons d'enlever les `.lock/`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/HTS221.lib
> +https://os.mbed.com/teams/ST/code/HTS221/#ccf7f36492ae
essayons d'enlever les `.lib`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM303AGR.lib
> +https://os.mbed.com/teams/ST/code/LSM303AGR/#6c7e83ae885e
essayons d'enlever les `.lib / .lock`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM303AGR/.lock/pid
> +10056
essayons d'enlever les `.lib / .lock`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM6DSOX.lib
> +https://os.mbed.com/teams/ST/code/LSM6DSOX/#f27ce43dee4f
essayons d'enlever les `.lib / .lock`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM6DSOX/.lock/pid
> +10056
essayons d'enlever les `.lib / .lock`

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-os.lib
> +https://github.com/ARMmbed/mbed-os/
sauf celui là.

2020-05-12 13:36 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Interface/DevI2C.h
> +class DevI2C : public I2C
le `public I2C` là il vient d'où? de mbed ou de ST?

2020-05-12 15:38 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Interface/DevI2C.h
> +class DevI2C : public I2C
La classe `DevI2C` vient de [X_NUCLEO_COMMON](https://os.mbed.com/teams/ST/code/X_NUCLEO_COMMON/), c'est un code de ST pour mbed.
Les capteurs HTS221 (température), LSM303AGR (boussole) et LSM6DSOX (accelerometre) sont dépendants de cette bibliothèque.

Et pour la classe `I2C`, il vient de mbed en effet :  https://github.com/ARMmbed/mbed-os/blob/master/drivers/I2C.h

2020-05-12 15:39 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/HTS221.lib
> +https://os.mbed.com/teams/ST/code/HTS221/#ccf7f36492ae
Il faudrait conserver l'origine des bibliothèques utilisées, je les rajoute dans le README

2020-05-12 15:50 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/HTS221/.lock/pid
> +10056
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/4e4038d62c0cb1583ab2f0143b464889e7e4cf56

2020-05-12 15:50 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/HTS221.lib
> +https://os.mbed.com/teams/ST/code/HTS221/#ccf7f36492ae
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/4e4038d62c0cb1583ab2f0143b464889e7e4cf56

2020-05-12 15:50 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM303AGR.lib
> +https://os.mbed.com/teams/ST/code/LSM303AGR/#6c7e83ae885e
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/4e4038d62c0cb1583ab2f0143b464889e7e4cf56

2020-05-12 15:50 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM303AGR/.lock/pid
> +10056
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/4e4038d62c0cb1583ab2f0143b464889e7e4cf56

2020-05-12 15:50 UTC, YannLocatelli commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Drivers/LSM6DSOX.lib
> +https://os.mbed.com/teams/ST/code/LSM6DSOX/#f27ce43dee4f
Fait dans le commit https://github.com/leka/LekaOS_Explorations/pull/5/commits/4e4038d62c0cb1583ab2f0143b464889e7e4cf56

2020-05-13 07:23 UTC, ladislas commented on LKExp-mbed-sensors/lib/mbed-ST_lib/Interface/DevI2C.h
> +class DevI2C : public I2C
okay je l'ai ! c'est une "extension" de l'I2C de mbed pour rajouter le registre dans la trame de données plutôt que de l'envoyer d'abord tout seul (pour le SPI ça marche comme ça, il y a deux `write`.

On se fera la même chose avec des noms plus clairs.

2020-05-14 17:39 UTC, merged